## Лабораторная работа №1 | Вариант 2

Выполнил: Касумова Наида, группа М8О-303Б-22

### 1. Numpy

In [53]:
import numpy as np

1. Создайте матрицу размером 8х8 и заполните ее шахматным рисунком

In [54]:
matrixChess = np.zeros((8, 8), dtype=int)

matrixChess[1::2, ::2] = 1
matrixChess[::2, 1::2] = 1

print(matrixChess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


2. Каков результат выполнения следующих выражений?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:
# Во всех трех случая возникает RuntimeErrorWarning

In [56]:
np.array(0) / np.array(0)
# Обнаружено недопустимое значение при делении

/var/folders/77/n41ltbh911dfbp1fqsms5r_80000gq/T/ipykernel_60661/2531629743.py:1: RuntimeWarning:

invalid value encountered in divide



np.float64(nan)

In [57]:
np.array(0) // np.array(0)
# Также обнаружено недопустимое деление, но при делении без остатка

/var/folders/77/n41ltbh911dfbp1fqsms5r_80000gq/T/ipykernel_60661/3073155191.py:1: RuntimeWarning:

divide by zero encountered in floor_divide



np.int64(0)

In [58]:
np.array([np.nan]).astype(int).astype(float)
# Получено недопустимое значение при приведении типов

/var/folders/77/n41ltbh911dfbp1fqsms5r_80000gq/T/ipykernel_60661/46106280.py:1: RuntimeWarning:

invalid value encountered in cast



array([0.])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [59]:
matrixChessTile = np.tile([[0, 1], [1, 0]], (4, 4))

print(matrixChessTile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. Как округлить до целых массив чисел с плавающей точкой?

In [60]:
arrRandom = np.random.rand(1, 3) * 10

arrRounded = np.round(arrRandom)

print(arrRandom)
print(arrRounded)

[[9.1537106  3.1624981  8.25288373]]
[[9. 3. 8.]]


5. Как найти общие значения между двумя массивами?

In [61]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

commonValues = np.intersect1d(arr1, arr2)

print(commonValues)

[3 4 5]


6. Как вычислить ((A+B)*(-A/2)) на месте (без копирования)?

In [62]:
A = np.random.rand(1, 3) * 10
B = np.random.rand(1, 3) * 10

print(A, B)

np.add(A, B, out=A)      # A = A + B
np.negative(A, out=A)    # A = -A
np.divide(A, 2, out=A)   # A = A / 2

print(A)

[[5.69568585 5.0535117  5.99844595]] [[7.5831596  6.65112102 5.12848885]]
[[-6.63942273 -5.85231636 -5.5634674 ]]


7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [63]:
coordinates = np.random.random((100, 2))

distances = np.sqrt(((coordinates[:, np.newaxis] - coordinates[np.newaxis, :]) ** 2).sum(axis=2))

print(distances)

[[0.         0.37291621 0.2199329  ... 0.24009671 0.03320888 0.43056838]
 [0.37291621 0.         0.28084279 ... 0.13632044 0.3426028  0.10536172]
 [0.2199329  0.28084279 0.         ... 0.1684524  0.21180692 0.28353175]
 ...
 [0.24009671 0.13632044 0.1684524  ... 0.         0.21163918 0.19420301]
 [0.03320888 0.3426028  0.21180692 ... 0.21163918 0.         0.4040559 ]
 [0.43056838 0.10536172 0.28353175 ... 0.19420301 0.4040559  0.        ]]


8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [64]:
arrFloat = np.array([1.5, 2.7, 3.2], dtype=np.float32)
print(arrFloat)

arrFloat = arrFloat.astype(np.int32, copy=False)

print(arrFloat)

[1.5 2.7 3.2]
[1 2 3]


9. Создайте структурированный массив, представляющий позицию (x, y) и цвет (r, g, b).

In [65]:
typeScalar = np.dtype('float32')

arrType = np.dtype([('position', 
                            [('x', typeScalar),
                             ('y', typeScalar)]),
                        ('color', 
                            [('r', typeScalar),
                             ('g', typeScalar),
                             ('b', typeScalar)])
                        ])
arr = np.zeros(2,  arrType)    
print(arr)

arr[0] = ((10., 100.), (255., 255., 255.))
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
[((10., 100.), (255., 255., 255.)) (( 0.,   0.), (  0.,   0.,   0.))]


10. Какой эквивалент enumerate для numpy массивов?

In [66]:
np.ndenumerate(arr)

### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Данные о преступлениях, совершенных женщинами в Индии, с демографическими подробностями.

Файл: `CrimesOnWomenData.csv`

```
State - название штата/региона
Year - год записи
Rape - случаи изнасилования
K&A - случаи похищения 
DD - смерти из-за приданого
AoW - нападение на женщин
AoM - нападение на женскую скромность(modestity)
DV - бытовое насилие
WT - торговля женщинами
```

In [67]:
import pandas as pd

In [68]:
data = "CrimesOnWomenData.csv"
df = pd.read_csv(data)
df.head(n = 10)

Unnamed: 0              State  Year  Rape   K&A   DD   AoW   AoM    DV  WT
0           0     ANDHRA PRADESH  2001   871   765  420  3544  2271  5791   7
1           1  ARUNACHAL PRADESH  2001    33    55    0    78     3    11   0
2           2              ASSAM  2001   817  1070   59   850     4  1248   0
3           3              BIHAR  2001   888   518  859   562    21  1558  83
4           4       CHHATTISGARH  2001   959   171   70  1763   161   840   0
5           5                GOA  2001    12     6    2    17     7    11   0
6           6            GUJARAT  2001   286   857   67   756   111  3667   0
7           7            HARYANA  2001   398   297  285   478   401  1513   0
8           8   HIMACHAL PRADESH  2001   124   105   10   310    14   317   0
9           9    JAMMU & KASHMIR  2001   169   504   13   622   288    50   0

1. За какие года представлен набор данных?

In [69]:
year = df['Year']

print('c', np.min(year), 'по', np.max(year))

c 2001 по 2021


2. Выявите район с самым высоким количеством убийств женщин

In [70]:
maxKillWomen = np.max(df['DD'])

print(df[df['DD'] == maxKillWomen][['State', 'DD']])

             State    DD
582  Uttar Pradesh  2524


3. Какое среднее число изнасилований женщин в индии наблюдалось в указанные года?

In [71]:
avgRapeWomen = np.average(df['Rape'])

print(avgRapeWomen)

727.8559782608696


4. Выявите район с минимальным числом похищений за период 2001-2003 года

In [72]:
KA = df[df['Year'].between(2001, 2003)]
filteredKA = KA.groupby('State').sum()
minKA = filteredKA['K&A'].idxmin()

print(minKA)

LAKSHADWEEP


5. Перечислите районы в которых наблюдались наиболее частые случае домашнего насилия за период с 2005 по 2012 года

In [73]:
DV = df[df['Year'].between(2005, 2012)].groupby('State').sum()
sortDV = DV.sort_values(by='DV', ascending=False)

print(sortDV.head())

                Unnamed: 0   Year   Rape    K&A     DD    AoW    AoM     DV  \
State                                                                         
WEST BENGAL           1488  12045  12433  10686   2806  12493    581  71821   
ANDHRA PRADESH        1326  12045   6861   8341   3265  27046  19868  62878   
RAJASTHAN             1452  12045   7761  11446   2531  14906    153  50834   
MAHARASHTRA           1410  12045   9136   5787   2288  20489   6312  43271   
UTTAR PRADESH         1476  12045   9372  23155  12124  14983  14386  42215   

                WT  
State               
WEST BENGAL     85  
ANDHRA PRADESH   3  
RAJASTHAN        3  
MAHARASHTRA      1  
UTTAR PRADESH    0  


6. Выведите названия районов в порядке не возрастания случаев торговли женщинами за 2020 год

In [74]:
WT = df[df['Year'] == 2020].sort_values(by='WT', ascending=False)
sortWT = WT['State'].head()

print(sortWT)

686            Sikkim
674         Jharkhand
677    Madhya Pradesh
684            Punjab
691       Uttarakhand
Name: State, dtype: object


Перейдем к следующему набору данных.

Файл: `CustomerPurchasingBehaviors.csv`

Этот набор данных содержит информацию о профилях клиентов и их покупательском поведении. Данные содержат столбцы, содержащие идентификатор пользователя, возраст, годовой доход, сумму покупки, показатель лояльности (в разбивке по классам), регион и частоту покупок. Он предназначен для анализа тенденций сегментации клиентов и лояльности и может быть использован для различных задач машинного обучения и анализа данных, связанных с поведением клиентов и исследованиями рынка.

```
user_id - ID клиента
age - Возраст
annual_income - Годовой доход клиента (в долларах США).
purchase_amount - Общая сумма покупок, совершенных клиентом (в долларах США).
loyalty_score - Показатель лояльности клиента (значение от 0 до 100).
region - Регион, в котором проживает клиент (Север, Юг, Восток, Запад).
purchase_frequency - Частота покупок клиентов (количество раз в год).
```

In [75]:
df = pd.read_csv('CustomerPurchasingBehaviors.csv')
df.head()

user_id  age  annual_income  purchase_amount  loyalty_score region  \
0        1   25          45000              200            4.5  North   
1        2   34          55000              350            7.0  South   
2        3   45          65000              500            8.0   West   
3        4   22          30000              150            3.0   East   
4        5   29          47000              220            4.8  North   

   purchase_frequency  
0                  12  
1                  18  
2                  22  
3                  10  
4                  13

8. Какой средний годовой доход у клиентов с уровнем лояльности больше 50 живущих на севере

In [76]:
filtInc = df[(df['loyalty_score'] > 5) & (df['region'] == 'North')]
avgInc = filtInc['annual_income'].mean()

print(avgInc)

60146.34146341463


9. Выведите 25 и 75 перцентили уровня лоальности клиентов живущих на западе с частотой покупок более 20 раз в год

In [77]:
filtLoyal = df[(df['purchase_frequency'] > 20) & (df['region'] == 'West')]
percent = filtLoyal['loyalty_score'].quantile([0.25, 0.75])

print(percent)

0.25    8.5
0.75    9.2
Name: loyalty_score, dtype: float64


10. Отличается ли медианный возраст клиентов с уровнем лояльности более 70 и менее 10 для жителей Востока и Севера.

In [78]:
filtMedian = df[((df['loyalty_score'] > 7) & (df['loyalty_score'] < 1)) & (df['region'].isin(['East', 'North']))]
medianAge = filtMedian['age'].median()
filtLowLoyalty = df[(df['loyalty_score'] < 10) & (df['region'].isin(['East', 'North']))]

print(filtLowLoyalty)

     user_id  age  annual_income  purchase_amount  loyalty_score region  \
0          1   25          45000              200            4.5  North   
3          4   22          30000              150            3.0   East   
4          5   29          47000              220            4.8  North   
7          8   27          43000              230            4.2   East   
8          9   50          70000              600            9.0  North   
..       ...  ...            ...              ...            ...    ...   
225      226   28          46000              250            4.2  North   
228      229   36          54000              400            6.5  North   
231      232   26          44000              240            4.3  North   
234      235   38          59000              430            6.9  North   
237      238   31          51000              340            5.6  North   

     purchase_frequency  
0                    12  
3                    10  
4                    

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

In [79]:
import plotly.graph_objects as go
import plotly.express as px

1. Постройте диаграмму которая отражает средний уровень лояльности во всех регионах

In [80]:
avg_loyalty_by_region = df.groupby('region')['loyalty_score'].mean().reset_index()

fig = px.bar(avg_loyalty_by_region, x='region', y='loyalty_score', 
             title='Average Loyalty Score by Region', 
             labels={'loyalty_score': 'Average Loyalty Score', 'region': 'Region'})

fig.show()

2. Постройте гистограмму распределения зарплат клиентов на Севере.

In [81]:
df[df['region'] == 'North']
fig = px.histogram(df, x = 'annual_income')
fig.show()

3. Сравните уровни зарплат людей на севере и юге.

In [82]:
fromNorth = df[df['region'] == 'North']['annual_income']
fromSouth =  df[df['region'] == 'South']['annual_income']

fig = go.Figure()

fig.add_trace(go.Histogram(x=fromNorth, name='From North', opacity=0.7))
fig.add_trace(go.Histogram(x=fromSouth, name='From South', opacity=0.7))

fig.update_xaxes(title_text='annual income')
fig.update_yaxes(title_text='count')
fig.update_layout(barmode='overlay')

fig.show()

4. Постройте box plot отображающий распределение уровня лояльности для людей до 20 лет, от 20 до 40, от 40 до 60 и старше 60 лет

In [83]:
def age_group(age):
    if age < 20:
        return 'До 20 лет'
    elif 20 <= age < 40:
        return '20-40 лет'
    elif 40 <= age < 60:
        return '40-60 лет'
    else:
        return 'Старше 60 лет'

df['age_group'] = df['age'].apply(age_group)

fig = px.box(df, 
             x='age_group', 
             y='loyalty_score',
             title='Распределение уровня лояльности по возрастным группам',
             labels={'age_group': 'Возрастная группа',
                     'loyalty_score': 'Уровень лояльности'})

fig.show()

5. Визуализируйте зависимость частоты покупок от заработка

In [84]:
fig = px.scatter(df, x='annual_income', y='purchase_frequency', 
                 title='Purchase Frequency vs Annual Income', 
                 labels={'annual_income': 'Annual Income', 'purchase_frequency': 'Purchase Frequency'},
                 trendline="ols")

fig.show()


6. Визуализируйте как зависит сумма покупок от зарплаты клиента

In [85]:
fig = px.scatter(df, x='annual_income', y='purchase_amount', 
                 title='Purchase Amount vs Annual Income', 
                 labels={'annual_income': 'Annual Income', 'purchase_amount': 'Purchase Amount'},
                 trendline="ols")

fig.show()


7. Придумайте как визуализировать зависимость между частотой покупок, суммой покупок и скором лояльности *

\* Задание на доп. балл

In [86]:
fig = px.scatter(df, 
                 x='purchase_frequency', 
                 y='purchase_amount',
                 color='loyalty_score',
                 size='annual_income',
                 hover_name='user_id',
                 title='Зависимость частоты покупок от суммы покупок с учетом срока лояльности',
                 labels={'purchase_frequency': 'Частота покупок',
                         'purchase_amount': 'Сумма покупок',
                         'loyalty_score': 'Срока лояльности'})

fig.show()